//! Per-subcommand modules.

pub mod admin;
pub mod auth;
pub mod chunks;
pub mod config;
pub mod doctor;
pub mod documents;
pub mod facets;
pub mod ingest;
pub mod keys;
pub mod login;
pub mod manifest;
pub mod mcp;
pub mod models;
pub mod ratelimits;
pub mod search;
pub mod skills;
pub mod sources;
pub mod status;
pub mod telemetry;
pub mod tokenlimits;
pub mod users;
pub mod version;
pub mod versions;
