use std::process::Command;

#[test]
fn manifest_init_writes_a_file() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("hierarchy.yaml");
    let exe = env!("CARGO_BIN_EXE_mnm");
    let status = Command::new(exe)
        .args(["manifest", "init", "-o"])
        .arg(&out)
        .status()
        .unwrap();
    assert!(status.success());
    assert!(out.exists());
    let body = std::fs::read_to_string(&out).unwrap();
    assert!(body.starts_with("# Generated by `mnm manifest init`"));
    assert!(body.contains("manifest_version: 1"));
}

#[test]
fn manifest_init_refuses_to_overwrite_without_force() {
    let dir = tempfile::tempdir().unwrap();
    let out = dir.path().join("hierarchy.yaml");
    std::fs::write(&out, "existing").unwrap();
    let exe = env!("CARGO_BIN_EXE_mnm");
    let status = Command::new(exe)
        .args(["manifest", "init", "-o"])
        .arg(&out)
        .status()
        .unwrap();
    assert!(!status.success());
}
