//! `mnm manifest init` — write a starter `hierarchy.yaml`.

use std::path::PathBuf;

use anyhow::{anyhow, Context as _, Result};
use clap::Args as ClapArgs;

/// Arguments for `mnm manifest init`.
#[derive(Debug, ClapArgs)]
pub struct Args {
    /// Output path (default `./hierarchy.yaml`).
    #[arg(short, long, default_value = "hierarchy.yaml")]
    pub output: PathBuf,
    /// Overwrite if the file already exists.
    #[arg(long)]
    pub force: bool,
}

/// Run `mnm manifest init`.
pub fn run(args: &Args) -> Result<()> {
    if args.output.exists() && !args.force {
        return Err(anyhow!(
            "refusing to overwrite {}; pass --force to replace",
            args.output.display()
        ));
    }
    let date = time::OffsetDateTime::now_utc().date();
    let body = body(&date.to_string());
    std::fs::write(&args.output, body)
        .with_context(|| format!("write {}", args.output.display()))?;
    eprintln!("wrote {}", args.output.display());
    Ok(())
}

fn body(date: &str) -> String {
    format!(
        "# Generated by `mnm manifest init` on {date}.
# Schema: crates/mn-content/src/manifest/mod.rs (manifest_version = 1).
#
# Each leaf node references one source file via `file:` (relative to the
# manifest's parent dir, or `--base` at generate time). Groups use `name:`
# and `children:` to nest. `published_url:` and `provenance:` on any node
# are inherited by descendants — declare them at the highest applicable
# node to avoid repetition. A node with `path:` auto-discovers every
# supported file under that directory.

manifest_version: 1
root:
  name: My Source
  # published_url: https://example.com/docs/
  children:
    - file: path/to/your/first.md
      # name: Pretty Title
      # published_url: https://example.com/docs/first/
"
    )
}
