manifest_version: 1
root:
  name: olanetsoft-compact-by-example
  path: .
  exclude:
    - "**/node_modules/**"
    - "**/dist/**"
    - "**/build/**"
    - "**/target/**"
    - "**/managed/**"
    - "**/.git/**"
    - "**/.github/**"
    - "**/.next/**"
    - "**/out/**"
    - "**/coverage/**"
    - "**/__snapshots__/**"
    - "**/.turbo/**"
    - "**/CODE_OF_CONDUCT.md"
    - "**/CONTRIBUTING.md"
    - "**/SECURITY.md"
  provenance:
    attribution: community
    verified: false
    tags: [trust:medium]
