//! Strip rules 1-4 (spec Strip rules / Code files) for source files.
//!
//! Covers license/copyright header blocks, mid-file license blocks,
//! decorative comment lines, and generated-file banners.

use std::ops::Range;
use std::sync::LazyLock;

use regex::Regex;

use super::comment_syntax::comment_syntax;
use super::lexer::{head_len, lex_blocks, CommentBlock};
use super::LicenseDetector;
use crate::code::language::Language;

/// Case-insensitive license/copyright keyword heuristic (spec rule 1).
static LICENSEISH: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(copyright|licensed under|license|SPDX-License-Identifier|all rights reserved|permission is hereby granted|warranty)",
    )
    .expect("static regex")
});

/// `SPDX-License-Identifier: <expr>` extractor (expr = rest of line).
static SPDX_TAG: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?im)^\s*SPDX-License-Identifier:\s*(\S[^\r\n]*?)\s*$").expect("static regex")
});

/// Generated-file banner markers (spec rule 4), case-insensitive substrings.
static GENERATED: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(@generated|DO NOT EDIT|Code generated by|Auto-?generated( by)?)")
        .expect("static regex")
});

/// A run of >= 5 identical punctuation/symbol chars (spec rule 3).
///
/// Built at runtime because backreferences aren't supported by `regex`;
/// implemented by hand in `collapse_runs` instead.
const DECORATIVE_RUN: usize = 5;

/// Everything `apply_code_rules` decided.
#[derive(Debug, Default)]
pub struct CodeRuleOutcome {
    /// Sorted, non-overlapping `(range, replacement)` edits.
    pub edits: Vec<(Range<usize>, String)>,
    /// SPDX expressions found (from SPDX tags, and Phase B detection).
    pub licenses: Vec<String>,
    /// True: whole file is generated -- caller should skip it.
    pub generated: bool,
    /// Bytes removed by license rules (stats).
    pub license_bytes: usize,
    /// Bytes removed/rewritten by the decorative rule (stats).
    pub decorative_bytes: usize,
}

/// Apply rules 1-4 to a code file.
///
/// `file_name` is the basename (for the `.d.ts` generated-skip exemption).
/// Detection input is capped at 8 KB.
#[must_use]
pub fn apply_code_rules(
    body: &str,
    lang: Language,
    file_name: &str,
    detector: Option<&dyn LicenseDetector>,
) -> CodeRuleOutcome {
    let mut out = CodeRuleOutcome::default();
    let Some(syntax) = comment_syntax(lang) else {
        return out;
    };
    let blocks = lex_blocks(body, &syntax);

    // Rule 4 -- generated banner in the first 10 raw lines (code only; the
    // caller guarantees kind == Code). `.d.ts` exempt (spec Non-goals).
    if !file_name.ends_with(".d.ts") {
        let in_window = blocks.iter().filter(|b| b.first_line < 10);
        if in_window.into_iter().any(|b| GENERATED.is_match(&b.text)) {
            out.generated = true;
            return out;
        }
    }

    let head = head_len(body, &blocks);
    let mut removed: Vec<Range<usize>> = Vec::new();

    for (i, block) in blocks.iter().enumerate() {
        let capped = &block.text[..block.text.len().min(8 * 1024)];
        let tag_expr = SPDX_TAG.captures(capped).map(|c| c[1].trim().to_owned());
        let licenseish = LICENSEISH.is_match(capped);
        let strip = if i < head {
            // Rule 1: head blocks strip on the heuristic alone.
            licenseish
        } else {
            // Rule 2: mid-file needs the heuristic pre-filter AND a tag or a
            // confident detection.
            licenseish && (tag_expr.is_some() || detector.and_then(|d| d.detect(capped)).is_some())
        };
        if strip {
            if let Some(expr) = tag_expr {
                push_unique(&mut out.licenses, expr);
            } else if let Some(expr) = detector.and_then(|d| d.detect(capped)) {
                push_unique(&mut out.licenses, expr);
            }
            out.license_bytes += block.span.len();
            removed.push(block.span.clone());
        }
    }

    for r in removed {
        out.edits.push((r, String::new()));
    }

    // Rule 3 -- decorative lines, applied to comment-only lines NOT already
    // inside a removed range.
    decorative_edits(body, &blocks, &mut out);

    out.edits.sort_by_key(|(r, _)| r.start);
    out
}

fn push_unique(v: &mut Vec<String>, s: String) {
    if !v.contains(&s) {
        v.push(s);
    }
}

/// Collapse >= `DECORATIVE_RUN` identical punctuation runs inside comment
/// lines.
///
/// Drops the whole line when no word characters remain (spec rule 3).
fn decorative_edits(body: &str, blocks: &[CommentBlock], out: &mut CodeRuleOutcome) {
    // Owned clones: holding `&Range` borrows of `out.edits` across the
    // `out.edits.push(...)` below is E0502.
    let already: Vec<Range<usize>> = out.edits.iter().map(|(r, _)| r.clone()).collect();
    let mut offset = 0usize;
    for line in body.split_inclusive('\n') {
        let start = offset;
        offset += line.len();
        let inside_removed = already.iter().any(|r| r.start <= start && start < r.end);
        let inside_block = blocks
            .iter()
            .any(|b| b.span.start <= start && start < b.span.end);
        if inside_removed || !inside_block {
            continue;
        }
        let content = line.strip_suffix('\n').unwrap_or(line);
        let collapsed = collapse_runs(content);
        if collapsed == content {
            continue;
        }
        let has_words = collapsed.chars().any(char::is_alphanumeric);
        if has_words {
            out.decorative_bytes += content.len() - collapsed.len();
            out.edits.push((start..start + content.len(), collapsed));
        } else {
            // Drop the entire line including its newline.
            out.decorative_bytes += line.len();
            out.edits.push((start..start + line.len(), String::new()));
        }
    }
}

/// Remove runs of >= `DECORATIVE_RUN` identical punctuation/symbol characters.
fn collapse_runs(line: &str) -> String {
    let mut result = String::with_capacity(line.len());
    let chars: Vec<char> = line.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        let mut j = i + 1;
        while j < chars.len() && chars[j] == c {
            j += 1;
        }
        let run = j - i;
        let punct = !c.is_alphanumeric() && !c.is_whitespace();
        if !(punct && run >= DECORATIVE_RUN) {
            for _ in 0..run {
                result.push(c);
            }
        }
        i = j;
    }
    result
}

/// Apply sorted, non-overlapping edits to `body`.
#[must_use]
pub fn apply_edits(body: &str, edits: &[(Range<usize>, String)]) -> String {
    let mut result = String::with_capacity(body.len());
    let mut cursor = 0usize;
    for (range, replacement) in edits {
        result.push_str(&body[cursor..range.start]);
        result.push_str(replacement);
        cursor = range.end;
    }
    result.push_str(&body[cursor..]);
    result
}

#[cfg(test)]
mod tests {
    use std::fmt::Write as _;

    use super::*;
    use crate::code::language::Language;

    const APACHE_HEADER: &str = "// Copyright 2024 Foo Corp\n// Licensed under the Apache License, Version 2.0 (the \"License\");\n// you may not use this file except in compliance with the License.\n";

    #[test]
    fn strips_head_license_block_without_detector() {
        let body = format!("{APACHE_HEADER}\nfn main() {{}}\n");
        let out = apply_code_rules(&body, Language::Rust, "main.rs", None);
        let stripped = apply_edits(&body, &out.edits);
        assert!(!stripped.contains("Licensed under"));
        assert!(stripped.contains("fn main()"));
        assert!(out.license_bytes > 0);
        assert!(out.licenses.is_empty(), "no detector => no IDs");
    }

    #[test]
    fn spdx_tag_yields_expression_without_detector() {
        let body = "// SPDX-License-Identifier: MIT OR Apache-2.0\nfn x() {}\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        assert_eq!(out.licenses, vec!["MIT OR Apache-2.0".to_owned()]);
        let stripped = apply_edits(body, &out.edits);
        assert!(!stripped.contains("SPDX-License-Identifier"));
    }

    #[test]
    fn mid_file_license_needs_tag_or_detector() {
        // A mid-file block matching the keyword heuristic but with no SPDX tag
        // and no detector must SURVIVE (spec rule 2 degraded mode).
        let body = "fn a() {}\n\n// This function is licensed to thrill.\nfn b() {}\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        let stripped = apply_edits(body, &out.edits);
        assert!(stripped.contains("licensed to thrill"));
    }

    #[test]
    fn mid_file_spdx_tagged_block_is_stripped() {
        let body = "fn a() {}\n\n// Copyright Foo\n// SPDX-License-Identifier: MIT\nfn b() {}\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        let stripped = apply_edits(body, &out.edits);
        assert!(!stripped.contains("SPDX-License-Identifier"));
        assert_eq!(out.licenses, vec!["MIT".to_owned()]);
    }

    #[test]
    fn doc_comment_mentioning_license_survives_head_when_not_licenseish() {
        // Head block WITHOUT any heuristic keyword survives.
        let body = "// Frobnicates the widget.\nfn frob() {}\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        assert!(out.edits.is_empty());
    }

    #[test]
    fn decorative_runs_collapse_and_empty_lines_drop() {
        let body = "// ===== Configuration =====\n// =============\nlet x = 1;\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        let stripped = apply_edits(body, &out.edits);
        // Runs are deleted but flanking spaces kept: `//  Configuration ` --
        // assert on the word, not the exact spacing (normalization trims later).
        assert!(stripped.contains("Configuration"));
        assert!(!stripped.contains("============="));
        assert!(out.decorative_bytes > 0);
    }

    #[test]
    fn letters_are_never_decorative() {
        let body = "// TODOOO aaaaa deadbeefdeadbeef\nlet x = 1;\n";
        let out = apply_code_rules(body, Language::Rust, "x.rs", None);
        let stripped = apply_edits(body, &out.edits);
        assert!(stripped.contains("TODOOO aaaaa"));
    }

    #[test]
    fn generated_banner_skips_file_but_not_dts() {
        let body = "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x\n";
        assert!(apply_code_rules(body, Language::Go, "x.pb.go", None).generated);
        let dts =
            "// Generated by dts-bundle-generator. DO NOT EDIT.\nexport declare const x: number;\n";
        assert!(!apply_code_rules(dts, Language::TypeScript, "x.d.ts", None).generated);
    }

    #[test]
    fn generated_banner_past_line_10_is_ignored() {
        let mut body = String::new();
        for i in 0..12 {
            writeln!(body, "let a{i} = {i};").unwrap();
        }
        body.push_str("// DO NOT EDIT below this line\nlet b = 2;\n");
        assert!(!apply_code_rules(&body, Language::Rust, "x.rs", None).generated);
    }

    #[test]
    fn edits_apply_cleanly() {
        assert_eq!(apply_edits("abcdef", &[(1..3, String::new()), (4..5, "X".into())]), "adXf");
    }
}
